name: 'Release - Stencil Storybook'

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Which release workflow should run?'
        required: true
        type: choice
        default: dev
        options:
          - dev
          - production
      bump:
        description: 'Semver bump for production releases.'
        required: false
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  id-token: write

jobs:
  run-dev:
    if: ${{ github.event.inputs.channel == 'dev' }}
    uses: ./.github/workflows/release-dev.yml
    secrets: inherit

  run-production:
    if: ${{ github.event.inputs.channel == 'production' }}
    uses: ./.github/workflows/release-production.yml
    secrets: inherit
    with:
      bump: ${{ github.event.inputs.bump }}
