name: 'Stencil Storybook Production Release'

on:
  workflow_call:
    inputs:
      bump:
        description: 'Semver bump to apply (patch, minor, major).'
        required: true
        type: string
        default: patch

permissions:
  contents: read
  id-token: write

jobs:
  publish_production:
    name: ðŸš€ Publish Production Build
    uses: ./.github/workflows/publish-npm.yml
    with:
      tag: latest
      version: ${{ inputs.bump }}
